// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (
  firstname, lastname
) VALUES (
  ?, ?
)
RETURNING id, firstname, lastname
`

type CreateUserParams struct {
	Firstname string
	Lastname  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Firstname, arg.Lastname)
	var i User
	err := row.Scan(&i.ID, &i.Firstname, &i.Lastname)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, firstname, lastname FROM user
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Firstname, &i.Lastname)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, firstname, lastname FROM user
ORDER BY name
`

func (q *Queries) ListUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Firstname, &i.Lastname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserFirstname = `-- name: UpdateUserFirstname :exec
UPDATE user
set firstname = ?
WHERE id = ?
`

type UpdateUserFirstnameParams struct {
	Firstname string
	ID        int64
}

func (q *Queries) UpdateUserFirstname(ctx context.Context, arg UpdateUserFirstnameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFirstname, arg.Firstname, arg.ID)
	return err
}

const updateUserLastname = `-- name: UpdateUserLastname :exec
UPDATE user
set lastname = ?
WHERE id = ?
`

type UpdateUserLastnameParams struct {
	Lastname string
	ID       int64
}

func (q *Queries) UpdateUserLastname(ctx context.Context, arg UpdateUserLastnameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastname, arg.Lastname, arg.ID)
	return err
}
